### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by k4t0mono** [wgroeneveld/dokuwiki-to-hugo#1]
Every time a try use it I get a `ModuleNotFoundError: No module named 'src'`

![screenshot from 2017-05-26 15-08-31](https://cloud.githubusercontent.com/assets/21297981/26507152/6a35c82e-4225-11e7-9d13-d1a18b424555.png)

**Comment by wgroeneveld** [comment]
I'm sorry I didn't even know an issue was posted. Is this still relevant or did you manage to fix it?

**Comment by calston** [comment]
Why not assume he didn't. 

main.py needs to be outside of `/src`

**Comment by wgroeneveld** [comment]
Done thanks to the other pull request.
