### ISSUE TITLE
SyntaxError: invalid syntax, while executing it

### ISSUE THREAD

**Issue by mfechner** [wgroeneveld/dokuwiki-to-hugo#4]
Hi,

I just found this handy tool to migrate my dokuwiki to hugo.
I copied now my dokuwiki to `/usr/home/idefix/tmp/dokuwiki_to_hugo/dokuwiki/` and cloned the tool to `~/tmp/dokuwiki_to_hugo/dokuwiki-to-hugo`

If I execute it with: `python src/main.py --dir='/usr/home/idefix/tmp/dokuwiki_to_hugo/dokuwiki/'`

I see the error message:
```
Traceback (most recent call last):
  File "src/main.py", line 3, in <module>
    from dokuwiki_to_hugo import DokuWikiToHugo
  File "/usr/home/idefix/tmp/dokuwiki_to_hugo/dokuwiki-to-hugo/src/dokuwiki_to_hugo.py", line 4
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
```

It seems that a broken version of `src/dokuwiki_to_hugo.py` was committed?

**Comment by wgroeneveld** [comment]
Sorry about that. People have been creating pull requests and I have been too careless in accepting them. It's a bit of a mess and I'm not happy about that. I quickly fixed the above issue, but thanks to the module movements, unit tests are broken. Urgh. I did the best I could in the short time that I can spend on this to fix this, but acceptance tests are still broken.

That means it _might_ still not work...

**Comment by mfechner** [comment]
Thanks a lot, executing the command `python src/main.py --dir='/usr/home/idefix/tmp/dokuwiki_to_hugo/dokuwiki/'` generates now a lot of files.
